#
# Copyright (C) 2018-2021 Niels Basjes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: PrefixMap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - '11'

    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Cache Local Maven Repository
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Build
      run: mvn -B install

    - name: Codecov
      uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
